import cv2

# window
WINDOW_SIZE_FLAG = cv2.WINDOW_AUTOSIZE  # WINDOW_NORMAL, WINDOW_AUTOSIZE, WINDOW_FULLSCREEN
WINDOW_STATE_FLAG = cv2.WND_PROP_VISIBLE
WINDOW_RESIZE_INTERPOLATION = cv2.INTER_AREA
WINDOW_ESC_KEY = 27
CONSOLE_ESC_KEY = 'esc'

# color maps
COLORIZER_CMAP = 2  # 0-Jet 1-Classic 2-WhiteToBlack 3-BlackToWhite 4-Bio 5-Cold 6-Warm 7-Quantized 8-Pattern
BGR_TO_RGB = cv2.COLOR_BGR2RGB

# RGB indices
COLOR_INDEX = {'r': 0, 'g': 1, 'b': 2}

# image processing
BBOX_COLOR = (0, 255, 0)
BBOX_THICKNESS = 2
BBOX_FONT = cv2.FONT_HERSHEY_COMPLEX
BBOX_TEXT_OFFSET = 5
BBOX_TEXT_THICKNESS = 0.5

# alert message
INFO_POS = (0, 30)
INFO_FONT = cv2.FONT_HERSHEY_SIMPLEX
INFO_SIZE = 1
INFO_COLOR = (0, 0, 255)  # BGR
INFO_BACKGROUND = (0, 0, 0)  # BGR
INFO_THICKNESS = 2
LINE_TYPE = cv2.LINE_AA